import 'package:flutter/material.dart';

final Map<String, List<IconData>> iconCategories = {
  'Food & Drink': [
    Icons.fastfood,
    Icons.restaurant,
    Icons.local_cafe,
    Icons.local_bar,
    Icons.wine_bar,
    Icons.kitchen,
    Icons.dining,
    Icons.cake,
    Icons.local_pizza,
    Icons.icecream,
    Icons.local_drink,
    Icons.bakery_dining,
    Icons.brunch_dining,
    Icons.coffee,
    Icons.ramen_dining,
    Icons.kebab_dining,
    Icons.egg,
    Icons.breakfast_dining,
    Icons.lunch_dining,
    Icons.dinner_dining,
    Icons.takeout_dining,
    Icons.set_meal,
    Icons.emoji_food_beverage,
    Icons.restaurant_menu,
    Icons.local_dining,
  ],

  'Shopping': [
    Icons.shopping_cart,
    Icons.shopping_bag,
    Icons.card_giftcard,
    Icons.wallet,
    Icons.store,
    Icons.local_mall,
    Icons.local_convenience_store,
    Icons.local_grocery_store,
    Icons.receipt,
    Icons.payment,
    Icons.credit_card,
    Icons.local_offer,
    Icons.shopping_basket,
    Icons.qr_code,
    Icons.barcode_reader,
    Icons.storefront,
    Icons.shopping_cart_checkout,
    Icons.sell,
    Icons.price_check,
  ],

  'Entertainment': [
    Icons.movie_outlined,
    Icons.videogame_asset,
    Icons.music_note,
    Icons.theater_comedy,
    Icons.games,
    Icons.tv,
    Icons.headset,
    Icons.sports_esports,
    Icons.casino,
    Icons.sports_bar,
    Icons.piano,
    Icons.mic,
    Icons.headphones,
    Icons.speaker,
    Icons.videocam,
    Icons.camera_roll,
    Icons.theater_comedy,
    Icons.stadium,
    Icons.attractions,
    Icons.celebration,
    Icons.party_mode,
    Icons.album,
    Icons.library_music,
    Icons.movie_creation,
    Icons.music_video,
  ],

  'Health & Fitness': [
    Icons.health_and_safety,
    Icons.local_hospital,
    Icons.local_pharmacy,
    Icons.fitness_center,
    Icons.medical_services,
    Icons.spa,
    Icons.directions_run,
    Icons.self_improvement,
    Icons.monitor_heart,
    Icons.masks,
    Icons.healing,
    Icons.local_florist,
    Icons.water_drop,
    Icons.bloodtype,
    Icons.psychology,
    Icons.personal_injury,
    Icons.emergency,
    Icons.vaccines,
    Icons.medical_information,
    Icons.sports_handball,
    Icons.sports_gymnastics_rounded,
    Icons.free_breakfast_outlined,
  ],

  'Education': [
    Icons.school_outlined,
    Icons.book,
    Icons.science,
    Icons.menu_book,
    Icons.history_edu,
    Icons.cast_for_education,
    Icons.local_library,
    Icons.edit_note,
    Icons.calculate,
    Icons.draw,
    Icons.language,
    Icons.translate,
    Icons.abc,
    Icons.numbers,
    Icons.functions,
    Icons.biotech,
    Icons.quiz,
    Icons.auto_stories,
  ],

  'Travel & Transport': [
    Icons.flight_takeoff,
    Icons.directions_car,
    Icons.train,
    Icons.directions_bus,
    Icons.directions_bike,
    Icons.local_gas_station,
    Icons.beach_access,
    Icons.surfing,
    Icons.hotel,
    Icons.map,
    Icons.directions_boat,
    Icons.local_taxi,
    Icons.two_wheeler,
    Icons.electric_car,
    Icons.flight,
    Icons.rocket_launch,
    Icons.sailing,
    Icons.hiking,
    Icons.kayaking,
    Icons.paragliding,
    Icons.downhill_skiing,
    Icons.local_airport,
    Icons.luggage,
    Icons.tour,
    Icons.traffic,
    Icons.train_outlined,
    Icons.car_rental,
    Icons.navigation,
  ],

  'Home & Utilities': [
    Icons.home_outlined,
    Icons.bed,
    Icons.cleaning_services,
    Icons.lightbulb,
    Icons.eco,
    Icons.bathtub,
    Icons.ac_unit,
    Icons.power,
    Icons.kitchen,
    Icons.living,
    Icons.weekend,
    Icons.chair,
    Icons.door_front_door,
    Icons.window,
    Icons.roofing,
    Icons.yard,
    Icons.garage,
    Icons.thermostat,
    Icons.gas_meter,
    Icons.electrical_services,
    Icons.plumbing,
    Icons.home_repair_service,
    Icons.apartment,
    Icons.house,
  ],

  'Finance': [
    Icons.trending_up,
    Icons.savings,
    Icons.credit_card,
    Icons.work,
    Icons.attach_money,
    Icons.account_balance,
    Icons.payment,
    Icons.currency_exchange,
    Icons.receipt_long,
    Icons.request_quote,
    Icons.payments,
    Icons.account_balance_wallet,
    Icons.monetization_on,
    Icons.money_off,
    Icons.swap_horiz,
    Icons.bar_chart,
    Icons.pie_chart,
    Icons.account_circle,
    Icons.show_chart,
    Icons.track_changes,
  ],

  'Family & Personal': [
    Icons.pets,
    Icons.family_restroom,
    Icons.child_care,
    Icons.star,
    Icons.person,
    Icons.group,
    Icons.cake,
    Icons.favorite,
    Icons.woman,
    Icons.man,
    Icons.elderly,
    Icons.baby_changing_station,
    Icons.pregnant_woman,
    Icons.escalator_warning,
    Icons.diversity_1,
    Icons.diversity_2,
    Icons.diversity_3,
    Icons.wc,
    Icons.emoji_people,
    Icons.house_rounded,
  ],

  'Technology': [
    Icons.computer,
    Icons.phone_android,
    Icons.camera_alt,
    Icons.brush,
    Icons.devices,
    Icons.laptop,
    Icons.print,
    Icons.scanner,
    Icons.router,
    Icons.network_wifi,
    Icons.developer_mode,
    Icons.code,
    Icons.bug_report,
    Icons.terminal,
    Icons.http,
    Icons.web,
    Icons.cloud,
    Icons.storage,
    Icons.sd_card,
    Icons.usb,
    Icons.bluetooth,
    Icons.smartphone,
    Icons.memory,
    Icons.smart_toy,
  ],

  'Sports': [
    Icons.sports_soccer,
    Icons.sports_basketball,
    Icons.sports_tennis,
    Icons.pool,
    Icons.sports_baseball,
    Icons.sports_cricket,
    Icons.sports_football,
    Icons.sports_golf,
    Icons.sports_handball,
    Icons.sports_hockey,
    Icons.sports_kabaddi,
    Icons.sports_martial_arts,
    Icons.sports_mma,
    Icons.sports_motorsports,
    Icons.sports_rugby,
    Icons.sports_volleyball,
    Icons.sports,
    Icons.fitness_center,
    Icons.self_improvement,
  ],

  'Other': [
    Icons.more_horiz,
    Icons.category,
    Icons.accessibility,
    Icons.alarm,
    Icons.announcement,
    Icons.build,
    Icons.construction,
    Icons.design_services,
    Icons.engineering,
    Icons.handyman,
    Icons.hardware,
    Icons.light,
    Icons.palette,
    Icons.pest_control,
    Icons.recycling,
    Icons.solar_power,
    Icons.wind_power,
    Icons.water_damage,
    Icons.warning,
    Icons.info,
    Icons.help,
    Icons.question_mark,
    Icons.settings,
    Icons.tune,
    Icons.timeline,
    Icons.history,
    Icons.map,
  ],

  'Beauty & Grooming': [
    Icons.brush,
    Icons.face,
    Icons.style,
    Icons.spa,
    Icons.cut,
    Icons.content_cut,
    Icons.shower,
  ],

  'Gifts & Donations': [
    Icons.card_giftcard,
    Icons.redeem,
    Icons.volunteer_activism,
    Icons.favorite,
    Icons.attach_money,
  ],

  'Subscriptions': [
    Icons.subscriptions,
    Icons.autorenew,
    Icons.repeat,
    Icons.credit_card,
  ],

  'Auto & Vehicle': [
    Icons.directions_car,
    Icons.car_rental,
    Icons.car_repair,
    Icons.ev_station,
    Icons.local_gas_station,
    Icons.motorcycle,
    Icons.directions_bus,
  ],

  'Work & Office': [
    Icons.work,
    Icons.business_center,
    Icons.account_box,
    Icons.source,
    Icons.meeting_room,
  ],

  'Hobbies & Crafts': [
    Icons.create,
    Icons.palette,
    Icons.toys,
    Icons.extension,
    Icons.local_play,
  ],

  'Gardening & Outdoor': [
    Icons.nature,
    Icons.park,
    Icons.terrain,
    Icons.grass,
    Icons.local_florist,
  ],
  
  'Insurance & Legal': [Icons.policy, Icons.gavel, Icons.shield, Icons.gavel],
};

// Predefined color choices
final List<Color> predefinedColors = [
  Colors.blue,
  Colors.cyan,
  Colors.indigoAccent,
  Colors.indigo,
  Colors.green,
  Colors.lightGreenAccent,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Colors.orange,
  Colors.deepOrange,
  Colors.red,
  Colors.pink,
  Colors.purpleAccent,
  Colors.purple,
  Colors.deepPurple,
  Colors.teal,
  Colors.tealAccent,
  Colors.brown,
  Colors.black,
  Colors.grey,
];
